name: PacmanInfiniteLoop31x21
width: 31
height: 21
grid:
  - "###############################"
  - "#.............................#"
  - "#.#######.###########.#######.#"
  - "#.#.....#.#.........#.#.....#.#"
  - "#.#.###.#.#.#.###.#.#.#.###.#.#"
  - "#.#.#...#.#.#.....#.#.#...#.#.#"
  - "#.#.#.###.#.#.###.#.#.###.#.#.#"
  - "#...#.......#.....#.......#...#"
  - "#####.#######.###.#######.#####"
  - "#...........#.....#...........#"
  - "#G#########...###...#########G#"
  - "#...........#.....#...........#"
  - "#####.#######.###.#######.#####"
  - "#...#.......#.....#.......#...#"
  - "#.#.#.###.#.#.###.#.#.###.#.#.#"
  - "#.#.#...#.#.#..P..#.#.#...#.#.#"
  - "#.#.###.#.#.#.###.#.#.#.###.#.#"
  - "#.#.....#.#.........#.#.....#.#"
  - "#.#######.###########.#######.#"
  - "#.............................#"
  - "###############################"