name: Stage Narrow Grid
width: 31
height: 21
grid:
  - "###############################"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#G#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#P#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
  - "###############################"